name: "Multi event pipelines / workflow"
on:
    push: # Event: Whenever a push is made to the repository on the master branch
        branches:
            - master
            - test


jobs:
    on-push: # job name
        runs-on: ubuntu-latest
        steps: # Step to executed in job
            - name: "Running on master push" # Step 1
            run: echo "Running on master push"

